VERSION 0.7

# ADD_KNOWN_HOSTS appends some known public keys into the $target_file
ADD_KNOWN_HOSTS:
    COMMAND
    ARG target_file=~/.ssh/known_hosts
    LET expanded_target_file="$(eval echo $target_file)"
    COPY +known-hosts/known_hosts /tmp/.
    RUN mkdir -p $(dirname $expanded_target_file) && cat /tmp/known_hosts >> $expanded_target_file
    RUN rm /tmp/known_hosts

# known-hosts is used to copy the known_hosts file into the build context (internal use)
known-hosts:
    FROM alpine:3.18
    COPY known_hosts .
    SAVE ARTIFACT known_hosts

test:
    BUILD ./tests+all
