VERSION --global-cache 0.7


# GRADLE_GET_MOUNT_CACHE sets the following entries in the calling environment:
# EARTHLY_GRADLE_USER_HOME_CACHE: Code of the mount cache for the gradle home.
# EARTHLY_GRADLE_PROJECT_CACHE: Code of the mount cache for the .gradle folder.
# Example:
#   DO gradle+GRADLE_GET_MOUNT_CACHE
#   RUN --mount=$EARTHLY_GRADLE_USER_HOME_CACHE --mount=$EARTHLY_GRADLE_PROJECT_CACHE gradle --no-daemon build
# Arguments:
#   - cache_prefix: To be used in both caches. By default: ${EARTHLY_TARGET_PROJECT_NO_TAG}#${OS_RELEASE}#earthly-gradle-cache
GRADLE_GET_MOUNT_CACHE:
    COMMAND
    ARG EARTHLY_TARGET_PROJECT_NO_TAG
    ARG OS_RELEASE=$(md5sum /etc/os-release | cut -d ' ' -f 1)
    ARG cache_prefix = "${EARTHLY_TARGET_PROJECT_NO_TAG}#${OS_RELEASE}#earthly-gradle-cache"
    IF [ "$GRADLE_USER_HOME" = "" ]
        ENV GRADLE_USER_HOME="$HOME/.gradle"
    END
    ENV EARTHLY_GRADLE_CACHE_PREFIX=$cache_prefix
    ENV EARTHLY_GRADLE_USER_HOME_CACHE="type=cache,mode=0777,id=$cache_prefix,sharing=shared,target=$GRADLE_USER_HOME"
    ENV EARTHLY_GRADLE_PROJECT_CACHE="type=cache,mode=0777,id=${cache_prefix}#project,sharing=shared,target=.gradle"
