VERSION 0.6

FROM alpine/git:2.36.3

# Estimates monthly active users of a GIT remote repo, based on past commits
active-users:
  ARG --required repoUrl
  RUN git clone --bare --filter=blob:none $repoUrl repo;
  RUN cd repo; \
      git --no-pager log -s --format="%ae" --since=30.days | grep -v @users.noreply.github.com | sort | uniq -c | awk '$1 >= 3 {print $0}' | wc -l
