VERSION 0.7

INSTALL:
    COMMAND
    COPY +install-dind-script/install-dind.sh /tmp/install-dind.sh
    RUN /tmp/install-dind.sh

install-dind-script:
    FROM alpine:3.18.4
    COPY ./install-dind.sh ./
    SAVE ARTIFACT ./install-dind.sh

test:
    BUILD ./tests+all
