VERSION 0.7

all:
    BUILD +test-install-dind-for-image \
        --base_image=docker:dind \
        --base_image=alpine:latest \
        --base_image=debian:stable \
        --base_image=debian:stable-slim \
        --base_image=debian:oldstable \
        --base_image=ubuntu:latest \
        --base_image=amazonlinux:1 \
        --base_image=amazonlinux:2 \
        --base_image=earthly/dind:alpine \
        --base_image=earthly/dind:ubuntu

test-install-dind-for-image:
    ARG --required base_image
    FROM alpine
    ARG TARGETPLATFORM
    IF [ "${base_image%:*}" = "amazonlinux" ] && [ "$TARGETPLATFORM" = "linux/arm64" ] # no amazonlinux:1 for arm64/function not supported atm for amazonlinux:2 on arm - skipping
        RUN echo skipping $base_image with platform $TARGETPLATFORM
    ELSE
        FROM "$base_image"
        # docker-compose will fail with:
        #     Error response from daemon: Invalid container name (-hello-1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
        # if docker-compose.yml is in the root directory, due to the --project flag defaulting to "".
        # This bug does not exist in the official earthly/dind:alpine image.
        WORKDIR /dind-test

        DO ..+INSTALL
        RUN echo "
    version: \"3\"
    services:
        hello:
            image: hello-world:latest
        " >./docker-compose.yml
        WITH DOCKER --compose docker-compose.yml
            RUN true
        END
    END
