VERSION --pass-args --arg-scope-and-set 0.7

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +test-add-known-hosts-image \
        --base_image=alpine:latest \
        --base_image=debian:stable \
        --base_image=debian:stable-slim \
        --base_image=ubuntu:latest \
        --base_image=amazonlinux:1 \
        --base_image=amazonlinux:2 \
        --target_file=~/to_interpolate/known_hosts \
        --target_file=no_dir_new_known_hosts \
        --target_file=/some/dir/to/file/new_known_hosts \
        --target_file=existing_known_hosts # this will be handled in the test target

test-add-known-hosts-image:
    ARG --required base_image
    ARG TARGETPLATFORM
    FROM alpine
    IF [ "$base_image" = "amazonlinux:1" ] && [ "$TARGETPLATFORM" = "linux/arm64" ] # no amazonlinux:1 for arm64, skipping
        RUN echo skipping $base_image with platform $TARGETPLATFORM
    ELSE
        FROM "$base_image"
        IF [ "$base_image" = "amazonlinux:1" ]
            RUN yum -y install diffutils.x86_64
        END
        COPY ..+known-hosts/known_hosts /tmp/expected-temp
        RUN test -s /tmp/expected-temp
        ARG target_file
        IF [ "$target_file" = "existing_known_hosts" ]
            RUN echo some-key >> /tmp/expected
            RUN echo some-key >> $target_file
        END
        RUN cat /tmp/expected-temp >> /tmp/expected
        DO --pass-args ..+ADD_KNOWN_HOSTS
        LET expanded_target_file="$(eval echo $target_file)"
        RUN diff /tmp/expected $(eval echo $expanded_target_file)
    END
