name: GitHub Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  test:
    name: +test
    runs-on: [earthly-satellite#gha-lib] # https://docs.earthly.dev/earthly-cloud/satellites/gha-runners
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: "5"
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_INSTALL_ID: "earthly-lib-githubactions"
    steps:
      - uses: actions/checkout@v2
      - name: Docker mirror login (non fork only)
        run: docker login registry-1.docker.io.mirror.corp.earthly.dev --username "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}" --password "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Configure Earthly to use mirror (non fork only)
        run: |-
          earthly config global.buildkit_additional_config "'[registry.\"docker.io\"]
          mirrors = [\"registry-1.docker.io.mirror.corp.earthly.dev\"]'"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Run tests
        run: |-
          earthly config git "{github.com: {auth: ssh, user: git}}" && \
          eval $(ssh-agent) && \
          earthly secrets --org earthly-technologies --project core get littleredcorvette-id_rsa | ssh-add - && \
          earthly --ci -P +test

  test-native-arm:
    name: +test-native-arm
    runs-on: [earthly-satellite#gha-arm-lib] # https://docs.earthly.dev/earthly-cloud/satellites/gha-runners
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: "5"
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_INSTALL_ID: "earthly-lib-githubactions"
    steps:
      - uses: actions/checkout@v2
      - name: Docker mirror login (non fork only)
        run: docker login registry-1.docker.io.mirror.corp.earthly.dev --username "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}" --password "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Configure Earthly to use mirror (non fork only)
        run: |-
          earthly config global.buildkit_additional_config "'[registry.\"docker.io\"]
          mirrors = [\"registry-1.docker.io.mirror.corp.earthly.dev\"]'"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Run tests
        run: |-
          earthly config git "{github.com: {auth: ssh, user: git}}" && \
          eval $(ssh-agent) && \
          earthly secrets --org earthly-technologies --project core get littleredcorvette-id_rsa | ssh-add - && \
          earthly --ci -P ./utils/dind+test
